minutesPerUnit: 15
samplesPerLevel: 1
trials:  3
# toggle: first half of level: labels, second half of level: no labels
showLabels: toggle #always never toggle
incrementLevelOnPositiveStreak: 5
decrementLevelOnNegativeStreak: 3
language: E
vocab: best25
spokenFeedback: true
silentMode: false

# the following not yet in UI
# activity animal body drink emotion food fruit game gesture kitchen 
# object person place plant role sport time transport vegetable 
# nosymemo nosymbols
categories: [nosymemo]
pressControlToUnfreeze: false
reducedAnimations: true
levelBadges: false
showHint: true
games: 
  gTouchPic:
    levels:
      0: 
        numPics: 2
      1: 
        numPics: 4
      2: 
        numPics: 9
      3: 
        numPics: 16
      4: 
        numPics: 25
      5: 
        numPics: 36
  gMissingLetter:
    levels:
      0:
        numMissing: 1
        posMissing: start
      1:
        numMissing: 2
        posMissing: start
      2:
        numMissing: 1
        posMissing: random
      3:
        numMissing: 2
        posMissing: random
      4:
        numMissing: 3
        posMissing: random
      5:
        numMissing: 5
        posMissing: random
  gMissingNumber:
    numMissing: 1
    minNum: 0
    maxNum: 99
    steps: 1
    posMissing: end
    ops: [add]
    seqLen: 5
    levels:
      0:
        maxNum: 10
      1:
        maxNum: 10
        ops: [subtract]
      2:
        maxNum: 10
        ops: [add,subtract]
      3:
        maxNum: 25
        ops: [add,subtract]
      4:
        maxNum: 50
        steps: [1,2,3]
        ops: [add]
      5:
        maxNum: 50
        steps: [1,2]
        ops: [add,subtract]
      6:
        posMissing: notStart
        maxNum: 99
        steps: [1,2]
        ops: [add,subtract]
      7:
        posMissing: notStart
        maxNum: 99
        steps: [1,2,3,4,5]
        ops: [add,subtract]
      8:
        posMissing: notStart
        maxNum: 99
        steps: [3,4,5,6,7,8,9,10]
        ops: [add,subtract]
  gSteps:
    contrast: 0.22
    colors: [blue1, violet, lightgreen, pink, red, yellow]
    levels:
      0: 
        numPics: 9
        numColors: 1
        numRepeat: 1
        numSteps: 2
      1: 
        numPics: 9
        numColors: 1
        numRepeat: 1
        numSteps: 3
      2: 
        numPics: 4
        numColors: 3
        numRepeat: 1
        numSteps: 2
      3: 
        numPics: 4
        numColors: 1
        numRepeat: 2
        numSteps: 2
      4: 
        numPics: 6
        numColors: 1
        numRepeat: 2
        numSteps: 2
      5: 
        numPics: 3
        numColors: 4
        numRepeat: 2
        numSteps: 2
      6: 
        numPics: 4
        numColors: 1
        numRepeat: 4
        numSteps: 2
      7: 
        numPics: 2
        numColors: 4
        numRepeat: 3
        numSteps: 2
  gSet:
    contrast: 0.22
    colors: [blue, violet, lightgreen, pink, red, yellow]
    levels:
      0: 
        numPics: 3
        numColors: 4
        numRepeat: 2
        numSteps: 2
      1: 
        numPics: 4
        numColors: 1
        numRepeat: 4
        numSteps: 2
      2: 
        numPics: 2
        numColors: 4
        numRepeat: 3
        numSteps: 2
  gElim:
    contrast: 0.22
    colors: [blue, violet, lightgreen, pink, red, yellow]
    levels:
      0: 
        numPics: 3
        numColors: 3
        numRepeat: 1
      1: 
        numPics: 3
        numColors: 1
        numRepeat: 3
      2: 
        numPics: 2
        numColors: 3
        numRepeat: 2
      3: 
        numPics: 3
        numColors: 4
        numRepeat: 2
      4: 
        numPics: 3
        numColors: 4
        numRepeat: 3
  gTouchColors:
    contrast: 0.32
    colors:
      - red
      - blue
      - yellow
      - green
    levels:
      0: 
        numPics: 2
        numColors: 2
      1: 
        numPics: 3
        numColors: 3
      2: 
        numPics: 4
        numColors: 3
      3: 
        numPics: 4
        numColors: 4
      4: 
        numPics: 5
        numColors: 4
  gPremem:
    trials: 1
    levels:
      0: 
        numPics: 2
        numRepeat: 2
      1: 
        numPics: 3
        numRepeat: 3
      2: 
        numPics: 6
        numRepeat: 2
      3: 
        numPics: 8
        numRepeat: 2
      4: 
        numPics: 12
        numRepeat: 2
      5: 
        numPics: 18
        numRepeat: 2
  gMem:
    levels:
      0: 
        numPics: 2
        numRepeat: 1
      1: 
        numPics: 4
        numRepeat: 1
      2: 
        numPics: 9
        numRepeat: 1
      3: 
        numPics: 2
        numRepeat: 1
      4: 
        numPics: 4
        numRepeat: 1
      5: 
        numPics: 4
        numRepeat: 1
      6: 
        numPics: 6
        numRepeat: 1
  gSayPic:
  gWritePic:
    levels:
      0: 
        maxWordLength: 4
      1: 
        maxWordLength: 6
      2: 
        maxWordLength: 8
      3: 
        maxWordLength: 100
  gAnagram:
    levels:
      0:
        maxWordLength: 3
      1:
        maxWordLength: 4
      2:
        maxWordLength: 5
      3:
        maxWordLength: 6
      4:
        maxWordLength: 7
      5:
        maxWordLength: 8

      