minutesPerUnit: 15
samplesPerLevel: 1
trials:  3
# toggle: first half of level: labels, second half of level: no labels
showLabels: toggle #always never toggle
incrementLevelOnPositiveStreak: 5
decrementLevelOnNegativeStreak: 3
language: E
vocab: best25
spokenFeedback: true
silentMode: false

# the following not yet in UI
# activity animal body drink emotion food fruit game gesture kitchen 
# object person place plant role sport time transport vegetable 
# nosymemo nosymbols
categories: [nosymemo]
pressControlToUnfreeze: false
reducedAnimations: true
levelBadges: false
showHint: true

      