views:
  areaTable: 
    layout: [MainBoard opps, gamePlayer]

areaTypes: #dictionary of multi use areas
  opps:
    owner: gsm.players.opponent #createForeach heisst 1 such opps.ID area
    layout: [stats, buildings]
    #will create opps.[id].stats and opps.[id].buildings
    #enter stats ones into stats,buildings one into areaTypes.stats
  gamePlayer: 
    layout: [stats, buildings, Hand]
  buildings: #implicit: one for each layout that has 'buildings'
    layout: [farms, estates chateaus]
  #all names that are not listed here are default area type = area

areaContent: #aus areas werden auch 'types' gemacht
#if find multiple area in areaTypes[key], each of thoses will get corresponding data inside
  MainBoard: Board
  opps: gsm.players.opponent.self
  gamePlayer: gsm.players.gamePlayer
  stats: [vps coins hand_size max_hand_size] #list of properties, default is: of owner
  farms: Farm
  estates: Estate
  chateaus: Chateau

visualize:
  Board:
    type: quadGrid
  Farm:
  Estate:
  Chateau:
    type: cardHand
  Card:
    type: c52
    map:
      rank: gsm.short_name
      suit: spades
  Tick:
    type: visual #default type, could omit!
    map:
      width: 80
      text: gsm.symbol
      fontSize: rsg.width
      color: gsm._player  

