program: #TODO: make this a list with ids
  minutesPerUnit: 15
  samplesPerLevel: 1
  # toggle: first half of level: labels, second half of level: no labels
  # TODO: individual adaptive: label toggle per word
  showLabels: toggle #always never toggle
  incrementLevelOnPositiveStreak: 5
  decrementLevelOnNegativeStreak: 3
  gameSequence:
    - game: gTouchPic
    - game: gPreMem
    - game: gMissingLetter
    - game: gSayPic
    - game: gWritePic
    - game: gTouchColors
  currentGameIndex: 0
  currentLevel: 5
  currentLanguage: E
  vocab: 25
  # activity animal body drink emotion food fruit game gesture kitchen 
  # object person place plant role sport time transport vegetable 
  # nosymemo nosymbols
  currentCategories: [nosymemo]
flags:
  pressControlToUnfreeze: false
  reducedAnimations: true
  levelBadges: false
games: 
  gTouchPic:
    levels:
      0: 
        numPics: 2
      1: 
        numPics: 4
      2: 
        numPics: 9
      3: 
        numPics: 16
      4: 
        numPics: 25
      5: 
        numPics: 36
  gMissingLetter:
    levels:
      0:
        numMissing: 1
        posMissing: start
      1:
        numMissing: 2
        posMissing: start
      2:
        numMissing: 1
        posMissing: random
      3:
        numMissing: 2
        posMissing: random
      4:
        numMissing: 3
        posMissing: random
      5:
        numMissing: 5
        posMissing: random
  gTouchColors:
    contrast: 0.32
    colors:
      - red
      - blue
      - yellow
      - green
    levels:
      0: 
        numPics: 2
        numColors: 2
      1: 
        numPics: 3
        numColors: 3
      2: 
        numPics: 4
        numColors: 3
      3: 
        numPics: 4
        numColors: 4
      4: 
        numPics: 5
        numColors: 4
  gPreMem:
    trials: 1
    levels:
      0: 
        numPics: 2
        numRepeat: 2
      1: 
        numPics: 3
        numRepeat: 3
      2: 
        numPics: 6
        numRepeat: 2
      3: 
        numPics: 8
        numRepeat: 2
      4: 
        numPics: 12
        numRepeat: 2
      5: 
        numPics: 18
        numRepeat: 2
  gSayPic:
    vocab: 75
    trials: 3
  gWritePic:
    levels:
      0: 
        maxWordLength: 4
      1: 
        maxWordLength: 6
      2: 
        maxWordLength: 8
      3: 
        maxWordLength: 100

      